### ISSUE TITLE
unexpected reply FAIL-BUSY for cmd SCAN

### ISSUE THREAD

**Issue by bopnrgi** [Oxmel/hotspot-connect#4]
Salut, merci pour ce travail !

J'ai fait une install toute fraiche de Raspberry pi 2
J'ai suivi les instructions à la lettre, et j'obtiens l'erreur en titre. Je suis bien allé fouillé, mais sans succès.

Pour votre information, une commande
`iwlist wlan0 scan`
retourne bien la liste des réseaux wifi présents autour de moi

J'ai tout de même réussi à aller plus loin après avoir tapé cette commande, mais avec un fail d'authentification. Et au bout de 2 ou 3 essais, je réobtiens l'erreur en titre. Ca ne semble pas déterministe... Beaucoup de mal à expliquer pourquoi !

PS : je suis en train d'essayer de l'adapter en bash only, avec du curl mais j'ai des petits soucis pour maintenir les sessions, y compris avec le cookie-jar

**Comment by Oxmel** [comment]
Salut @bopnrgi et merci d'avoir pris le temps de poster.

Ce type d'erreur se produit en général quand wpa_supplicant reçoit plusieurs commandes dans un laps de temps trop court. Donc ça veut dire que j'ai dû paramétrer des timings un peu trop agressifs entre l'envoi de plusieurs commandes.

Pourtant ça n'est pas faute d'avoir effectué des tests avant la release. Mais comme j'ai utilisé un Raspberry Pi Zero pour ça il est possible que ça soit lié à la vitesse d'exécution du script qui doit être différente de l'un à l'autre. Etant donné que le Pi 2 a plus de puissance.

Quoi qu'il en soit je vais faire quelques tests sur un Raspberry Pi 2 dans les mêmes conditions pour vérifier si j'arrive à reproduire le bug. Dans tous les cas ça ne devrait pas me prendre beaucoup de temps pour le régler. Je vous préviens dès qu'un patch sera dispo.

**Comment by Oxmel** [comment]
Bonne nouvelle, j'ai pu reproduire le bug en testant sur une machine plus puissante, et effectivement le timing était trop court sur la fonction qui s'occupe de lancer un scan. 

J'ai créé une branche temporaire qui contient le patch (commit : 82c452a),  vous pouvez le tester et me dire si ça règle bien le problème de votre côté? 

    $ git pull
    $ git checkout fix-issue-fail-busy
    $ python hotspot-connect.py

**Comment by Oxmel** [comment]
Après avoir effectué quelques tests supplémentaires, les crash au démarrage semblent avoir disparu avec ce patch, mais ça ne règle pas totalement le problème. Et d'autres crash, plus rares cette fois, peuvent quand même apparaître si certaines conditions sont réunies.

Dans l'immédiat vous pouvez utiliser la branche `fix-issue-fail-busy` pour empêcher les crash au démarrage et je laisse cette issue ouverte le temps de réécrire la fonction de scan pour corriger définitivement ce bug.

**Comment by Oxmel** [comment]
Le problème devrait être corrigé pour de bon cette fois, encore merci pour le retour de bug :-)
Si d'autres erreurs apparaissent, n'hésitez pas à ouvrir une nouvelle issue.

**Comment by bopnrgi** [comment]
Bonjour, je prends à l'instant connaissance de tous ces messages !
Mes activités professionnelles ne m'ont guerre laissé de temps pour avancer sur le sujet, mais je vois que ce n'est pas le cas de tout le monde :)
Quelle réactivité !! Bravo je vais tester ca

**Comment by Oxmel** [comment]
A vrai dire c'est tombé pile au bon moment puisque j'étais en vacances cette semaine. 
Content de voir que ce script peut être utile à quelqu'un :)
